//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/TopDownFreeCam/CameraControlInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @CameraControlInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @CameraControlInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""CameraControlInput"",
    ""maps"": [
        {
            ""name"": ""PCEditingCam"",
            ""id"": ""339d89dc-af4e-454c-824a-9d42a7439508"",
            ""actions"": [
                {
                    ""name"": ""MiddleBtnPress"",
                    ""type"": ""Button"",
                    ""id"": ""445279c8-1103-40b6-8eb5-6bf02ce1693a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MiddleBtnRelease"",
                    ""type"": ""Button"",
                    ""id"": ""f89a2f19-3c35-40b0-9d0d-39ad755687a6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightBtnPress"",
                    ""type"": ""Button"",
                    ""id"": ""6c8cc3da-4f1f-444f-99bd-cd8cb3787ba5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightBtnRelease"",
                    ""type"": ""Button"",
                    ""id"": ""1ea9098c-a9d4-4966-94a4-98ce4ceaf48c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(pressPoint=0.01)"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SpaceKeyPress"",
                    ""type"": ""Button"",
                    ""id"": ""8fe61c4c-e66f-4f96-b243-cd73647ae4f8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Scroll"",
                    ""type"": ""Value"",
                    ""id"": ""179beba4-310c-4301-b2e4-8edc346d858c"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MouseDelta"",
                    ""type"": ""Value"",
                    ""id"": ""f778c90b-4e68-408e-b8a1-3a45e8dfcd18"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MousePositioning"",
                    ""type"": ""Value"",
                    ""id"": ""4159caa8-ab50-41c0-8ebf-ecf457b0d78c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1f6c7206-271b-4378-8f8b-a642d0818436"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MiddleBtnPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6b71182b-9ae1-421e-8ded-ac7b8b263735"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightBtnPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5f933c79-c0ba-4abe-b380-b2bdd2767de1"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpaceKeyPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab088f68-fb2d-461e-9b8a-c6851451a59d"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Scroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d65f3824-a063-4433-97e0-a7a52dca3670"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseDelta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6ba246b6-36c3-462c-b50d-810017d7721d"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePositioning"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""32bd95a6-f99a-4bde-b568-f5db8a30c83e"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": ""Press(pressPoint=0.01,behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MiddleBtnRelease"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f91e6914-793c-4167-9bb4-b17ca3a8572e"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Press(pressPoint=0.01,behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightBtnRelease"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PCEditingCam
        m_PCEditingCam = asset.FindActionMap("PCEditingCam", throwIfNotFound: true);
        m_PCEditingCam_MiddleBtnPress = m_PCEditingCam.FindAction("MiddleBtnPress", throwIfNotFound: true);
        m_PCEditingCam_MiddleBtnRelease = m_PCEditingCam.FindAction("MiddleBtnRelease", throwIfNotFound: true);
        m_PCEditingCam_RightBtnPress = m_PCEditingCam.FindAction("RightBtnPress", throwIfNotFound: true);
        m_PCEditingCam_RightBtnRelease = m_PCEditingCam.FindAction("RightBtnRelease", throwIfNotFound: true);
        m_PCEditingCam_SpaceKeyPress = m_PCEditingCam.FindAction("SpaceKeyPress", throwIfNotFound: true);
        m_PCEditingCam_Scroll = m_PCEditingCam.FindAction("Scroll", throwIfNotFound: true);
        m_PCEditingCam_MouseDelta = m_PCEditingCam.FindAction("MouseDelta", throwIfNotFound: true);
        m_PCEditingCam_MousePositioning = m_PCEditingCam.FindAction("MousePositioning", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PCEditingCam
    private readonly InputActionMap m_PCEditingCam;
    private IPCEditingCamActions m_PCEditingCamActionsCallbackInterface;
    private readonly InputAction m_PCEditingCam_MiddleBtnPress;
    private readonly InputAction m_PCEditingCam_MiddleBtnRelease;
    private readonly InputAction m_PCEditingCam_RightBtnPress;
    private readonly InputAction m_PCEditingCam_RightBtnRelease;
    private readonly InputAction m_PCEditingCam_SpaceKeyPress;
    private readonly InputAction m_PCEditingCam_Scroll;
    private readonly InputAction m_PCEditingCam_MouseDelta;
    private readonly InputAction m_PCEditingCam_MousePositioning;
    public struct PCEditingCamActions
    {
        private @CameraControlInput m_Wrapper;
        public PCEditingCamActions(@CameraControlInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @MiddleBtnPress => m_Wrapper.m_PCEditingCam_MiddleBtnPress;
        public InputAction @MiddleBtnRelease => m_Wrapper.m_PCEditingCam_MiddleBtnRelease;
        public InputAction @RightBtnPress => m_Wrapper.m_PCEditingCam_RightBtnPress;
        public InputAction @RightBtnRelease => m_Wrapper.m_PCEditingCam_RightBtnRelease;
        public InputAction @SpaceKeyPress => m_Wrapper.m_PCEditingCam_SpaceKeyPress;
        public InputAction @Scroll => m_Wrapper.m_PCEditingCam_Scroll;
        public InputAction @MouseDelta => m_Wrapper.m_PCEditingCam_MouseDelta;
        public InputAction @MousePositioning => m_Wrapper.m_PCEditingCam_MousePositioning;
        public InputActionMap Get() { return m_Wrapper.m_PCEditingCam; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PCEditingCamActions set) { return set.Get(); }
        public void SetCallbacks(IPCEditingCamActions instance)
        {
            if (m_Wrapper.m_PCEditingCamActionsCallbackInterface != null)
            {
                @MiddleBtnPress.started -= m_Wrapper.m_PCEditingCamActionsCallbackInterface.OnMiddleBtnPress;
                @MiddleBtnPress.performed -= m_Wrapper.m_PCEditingCamActionsCallbackInterface.OnMiddleBtnPress;
                @MiddleBtnPress.canceled -= m_Wrapper.m_PCEditingCamActionsCallbackInterface.OnMiddleBtnPress;
                @MiddleBtnRelease.started -= m_Wrapper.m_PCEditingCamActionsCallbackInterface.OnMiddleBtnRelease;
                @MiddleBtnRelease.performed -= m_Wrapper.m_PCEditingCamActionsCallbackInterface.OnMiddleBtnRelease;
                @MiddleBtnRelease.canceled -= m_Wrapper.m_PCEditingCamActionsCallbackInterface.OnMiddleBtnRelease;
                @RightBtnPress.started -= m_Wrapper.m_PCEditingCamActionsCallbackInterface.OnRightBtnPress;
                @RightBtnPress.performed -= m_Wrapper.m_PCEditingCamActionsCallbackInterface.OnRightBtnPress;
                @RightBtnPress.canceled -= m_Wrapper.m_PCEditingCamActionsCallbackInterface.OnRightBtnPress;
                @RightBtnRelease.started -= m_Wrapper.m_PCEditingCamActionsCallbackInterface.OnRightBtnRelease;
                @RightBtnRelease.performed -= m_Wrapper.m_PCEditingCamActionsCallbackInterface.OnRightBtnRelease;
                @RightBtnRelease.canceled -= m_Wrapper.m_PCEditingCamActionsCallbackInterface.OnRightBtnRelease;
                @SpaceKeyPress.started -= m_Wrapper.m_PCEditingCamActionsCallbackInterface.OnSpaceKeyPress;
                @SpaceKeyPress.performed -= m_Wrapper.m_PCEditingCamActionsCallbackInterface.OnSpaceKeyPress;
                @SpaceKeyPress.canceled -= m_Wrapper.m_PCEditingCamActionsCallbackInterface.OnSpaceKeyPress;
                @Scroll.started -= m_Wrapper.m_PCEditingCamActionsCallbackInterface.OnScroll;
                @Scroll.performed -= m_Wrapper.m_PCEditingCamActionsCallbackInterface.OnScroll;
                @Scroll.canceled -= m_Wrapper.m_PCEditingCamActionsCallbackInterface.OnScroll;
                @MouseDelta.started -= m_Wrapper.m_PCEditingCamActionsCallbackInterface.OnMouseDelta;
                @MouseDelta.performed -= m_Wrapper.m_PCEditingCamActionsCallbackInterface.OnMouseDelta;
                @MouseDelta.canceled -= m_Wrapper.m_PCEditingCamActionsCallbackInterface.OnMouseDelta;
                @MousePositioning.started -= m_Wrapper.m_PCEditingCamActionsCallbackInterface.OnMousePositioning;
                @MousePositioning.performed -= m_Wrapper.m_PCEditingCamActionsCallbackInterface.OnMousePositioning;
                @MousePositioning.canceled -= m_Wrapper.m_PCEditingCamActionsCallbackInterface.OnMousePositioning;
            }
            m_Wrapper.m_PCEditingCamActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MiddleBtnPress.started += instance.OnMiddleBtnPress;
                @MiddleBtnPress.performed += instance.OnMiddleBtnPress;
                @MiddleBtnPress.canceled += instance.OnMiddleBtnPress;
                @MiddleBtnRelease.started += instance.OnMiddleBtnRelease;
                @MiddleBtnRelease.performed += instance.OnMiddleBtnRelease;
                @MiddleBtnRelease.canceled += instance.OnMiddleBtnRelease;
                @RightBtnPress.started += instance.OnRightBtnPress;
                @RightBtnPress.performed += instance.OnRightBtnPress;
                @RightBtnPress.canceled += instance.OnRightBtnPress;
                @RightBtnRelease.started += instance.OnRightBtnRelease;
                @RightBtnRelease.performed += instance.OnRightBtnRelease;
                @RightBtnRelease.canceled += instance.OnRightBtnRelease;
                @SpaceKeyPress.started += instance.OnSpaceKeyPress;
                @SpaceKeyPress.performed += instance.OnSpaceKeyPress;
                @SpaceKeyPress.canceled += instance.OnSpaceKeyPress;
                @Scroll.started += instance.OnScroll;
                @Scroll.performed += instance.OnScroll;
                @Scroll.canceled += instance.OnScroll;
                @MouseDelta.started += instance.OnMouseDelta;
                @MouseDelta.performed += instance.OnMouseDelta;
                @MouseDelta.canceled += instance.OnMouseDelta;
                @MousePositioning.started += instance.OnMousePositioning;
                @MousePositioning.performed += instance.OnMousePositioning;
                @MousePositioning.canceled += instance.OnMousePositioning;
            }
        }
    }
    public PCEditingCamActions @PCEditingCam => new PCEditingCamActions(this);
    public interface IPCEditingCamActions
    {
        void OnMiddleBtnPress(InputAction.CallbackContext context);
        void OnMiddleBtnRelease(InputAction.CallbackContext context);
        void OnRightBtnPress(InputAction.CallbackContext context);
        void OnRightBtnRelease(InputAction.CallbackContext context);
        void OnSpaceKeyPress(InputAction.CallbackContext context);
        void OnScroll(InputAction.CallbackContext context);
        void OnMouseDelta(InputAction.CallbackContext context);
        void OnMousePositioning(InputAction.CallbackContext context);
    }
}
